services:
  web:
    build: .
    command: sh -c "uvicorn main:app --host 0.0.0.0 --port ${PORT:-8000}"
    environment:
      PORT: "8000"
    expose:
      - "8000"
    ports:
      - "127.0.0.1:8000:8000"
    restart: always